# Generated by Django 2.2.7 on 2020-01-16 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Изображение')),
                ('slug', models.TextField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
