# Generated by Django 2.2.7 on 2020-01-22 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands_model',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
    ]
