# Generated by Django 2.2.7 on 2020-07-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0003_productsize_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'product_tone',
                'managed': False,
            },
        ),
    ]
